#!/bin/bash
# Git Clean State Stop Hook
# Ensures branch naming, PR template usage, and all changes are committed/pushed before Claude Code completes

set -euo pipefail

# Read the JSON input from stdin
input=$(cat)

# Prevent infinite loops by limiting stop hook runs
MAX_HOOK_RUNS=3
HOOK_COUNT_FILE="/tmp/git-clean-state-hook-count"

if [[ ! -f "$HOOK_COUNT_FILE" ]]; then
  echo 0 > "$HOOK_COUNT_FILE"
fi

hook_count=$(cat "$HOOK_COUNT_FILE")
if [[ "$hook_count" -ge "$MAX_HOOK_RUNS" ]]; then
  rm -f "$HOOK_COUNT_FILE"
  exit 0
fi
echo $((hook_count + 1)) > "$HOOK_COUNT_FILE"

# Check if we're in a git repository - bail if not
if ! git rev-parse --git-dir >/dev/null 2>&1; then
  exit 0
fi

REPO_DIR=$(git rev-parse --show-toplevel)
SNAPSHOT_FILE="/opt/claude-hooks/remote-branches-snapshot"
PR_TEMPLATE_MARKER="Generated by Glean Code Writer"

if [[ -f /opt/claude-hooks/branch-guard.sh ]]; then
  source /opt/claude-hooks/branch-guard.sh
fi

if command -v ensure_branch_ok >/dev/null 2>&1; then
  if ! ensure_branch_ok "$REPO_DIR" "$SNAPSHOT_FILE"; then
    print_branch_guard_block "complete" && exit 0
  fi
fi

current_branch=$(git -C "$REPO_DIR" branch --show-current)

# Check PR uses Glean template (if template exists and there's an open PR)
# This ensures PRs include the Glean Code Writer branding and chat link
GLEAN_TEMPLATE="/workspace/tmp/pull_request_template_glean_code_writer.md"
if [[ -f "$GLEAN_TEMPLATE" && -n "$current_branch" ]]; then
  # Parse owner/repo from remote URL
  remote_url=$(git remote get-url origin 2>/dev/null) || remote_url=""
  if [[ -n "$remote_url" && "$remote_url" =~ github\.com[:/]([^/]+)/([^/.]+) ]]; then
    owner="${BASH_REMATCH[1]}"
    repo="${BASH_REMATCH[2]}"
    repo="${repo%.git}"

    # Check for open PR on this branch (fail silently if API unavailable)
    pr_response=$(gh api "repos/$owner/$repo/pulls?head=$owner:$current_branch&state=open" 2>/dev/null) || pr_response="[]"

    if [[ "$pr_response" != "[]" && "$pr_response" != "" ]]; then
      pr_body=$(echo "$pr_response" | jq -r '.[0].body // ""')
      pr_number=$(echo "$pr_response" | jq -r '.[0].number // ""')

      # Check if PR body contains the template marker
      if ! echo "$pr_body" | grep -qF "$PR_TEMPLATE_MARKER"; then
        cat >&2 <<EOF
❌ Cannot complete: PR #$pr_number doesn't use template.

Please update the PR description:
1. Read the template: cat $GLEAN_TEMPLATE
2. Update the PR with the template content:
   gh api repos/$owner/$repo/pulls/$pr_number --method PATCH -f body="\$(cat $GLEAN_TEMPLATE)"

EOF
        echo '{"decision":"block","reason":"PR #'"$pr_number"' must use the template. Update with: gh api repos/'"$owner"'/'"$repo"'/pulls/'"$pr_number"' --method PATCH -f body=\"\$(cat '"$GLEAN_TEMPLATE"')\""}'
        exit 0
      fi
    fi
  fi
fi

# Check for uncommitted changes (both staged and unstaged)
if ! git diff --quiet || ! git diff --cached --quiet; then
  cat >&2 <<EOF
❌ Cannot complete: uncommitted changes detected

Remember, this is an ephemeral sandbox, and we want changes to be persisted.
There are uncommitted changes in the repository.
Please commit and push these changes to the remote branch before completion.

Run: git status
EOF
  # Block completion by outputting JSON decision
  echo '{"decision":"block","reason":"This is an ephemeral sandbox and uncommitted changes will be lost. Run git status, commit all changes, and push to the remote branch before completing."}'
  exit 0
fi

# Check for untracked files that might be important
untracked_files=$(git ls-files --others --exclude-standard)
if [[ -n "$untracked_files" ]]; then
  cat >&2 <<EOF
❌ Cannot complete: untracked files detected

Remember, this is an ephemeral sandbox, and we want changes to be persisted.
There are untracked files in the repository:
$untracked_files

Please commit and push these changes to the remote branch before completion.
EOF
  echo '{"decision":"block","reason":"This is an ephemeral sandbox and untracked files will be lost. Add these files with git add, commit them, and push to the remote branch before completing."}'
  exit 0
fi

# Check for unpushed commits
if [[ -n "$current_branch" ]]; then
  if git rev-parse "origin/$current_branch" >/dev/null 2>&1; then
    # Branch exists on remote - compare against it
    unpushed=$(git rev-list "origin/$current_branch..HEAD" --count 2>/dev/null) || unpushed=0
    if [[ "$unpushed" -gt 0 ]]; then
      cat >&2 <<EOF
❌ Cannot complete: unpushed commits detected

Remember, this is an ephemeral sandbox, and we want changes to be persisted.
There are $unpushed unpushed commit(s) on branch '$current_branch'.
Please push these changes to the remote repository before completion.

Run: git push
EOF
      echo '{"decision":"block","reason":"This is an ephemeral sandbox and unpushed commits will be lost. Run git push to save your work to the remote branch before completing."}'
      exit 0
    fi
  else
    # Branch doesn't exist on remote - check for commits not on any remote branch
    # This correctly handles branches created from non-default branches
    unpushed=$(git rev-list HEAD --not --remotes --count 2>/dev/null) || unpushed=0
    if [[ "$unpushed" -gt 0 ]]; then
      cat >&2 <<EOF
❌ Cannot complete: unpushed commits on new branch

Remember, this is an ephemeral sandbox, and we want changes to be persisted.
Branch '$current_branch' has $unpushed unpushed commit(s) that are not on any remote branch.
Please push these changes to the remote repository before completion.

Run: git push --set-upstream origin $current_branch
EOF
      echo '{"decision":"block","reason":"This is an ephemeral sandbox and this new branch with unpushed commits will be lost. Run git push --set-upstream origin '"$current_branch"' to save your work before completing."}'
      exit 0
    fi
  fi
fi

# All checks passed - clean up counter and add label to PR if one exists
rm -f "$HOOK_COUNT_FILE" 2>/dev/null || true

if [[ -n "$current_branch" ]]; then
  AGENT_LABEL_NAME="glean-code-writer"
  AGENT_LABEL_COLOR="343CED"
  AGENT_LABEL_DESCRIPTION="Modified by Glean Code Writer"

  # Parse owner/repo if not already set
  if [[ -z "${owner:-}" || -z "${repo:-}" ]]; then
    remote_url=$(git remote get-url origin 2>/dev/null) || remote_url=""
    if [[ -n "$remote_url" && "$remote_url" =~ github\.com[:/]([^/]+)/([^/.]+) ]]; then
      owner="${BASH_REMATCH[1]}"
      repo="${BASH_REMATCH[2]}"
      repo="${repo%.git}"
    fi
  fi

  if [[ -n "${owner:-}" && -n "${repo:-}" ]]; then
    # Get PR number via REST API
    label_pr_number=$(gh api "repos/$owner/$repo/pulls?head=$owner:$current_branch&state=open" --jq '.[0].number // empty' 2>/dev/null || echo "")
    if [[ -n "$label_pr_number" ]]; then
      label_path=$(printf '%s' "$AGENT_LABEL_NAME" | jq -sRr @uri 2>/dev/null || echo "$AGENT_LABEL_NAME")

      if ! gh api "repos/$owner/$repo/labels/$label_path" >/dev/null 2>&1; then
        gh api "repos/$owner/$repo/labels" --method POST \
          -f "name=$AGENT_LABEL_NAME" \
          -f "color=$AGENT_LABEL_COLOR" \
          -f "description=$AGENT_LABEL_DESCRIPTION" \
          >/dev/null 2>&1 || true
      fi

      # Add label via REST API
      gh api "repos/$owner/$repo/issues/$label_pr_number/labels" --method POST -f "labels[]=$AGENT_LABEL_NAME" >/dev/null 2>&1 || true
    fi
  fi
fi

exit 0
