#!/bin/bash
# Install the Glean Code Writer branding wrapper without disrupting repo hooks.
set -euo pipefail

REPO_DIR="$(cd "${1:-.}" && pwd -P)"
HOOKS_DIR="$(git -C "$REPO_DIR" config --path core.hooksPath 2>/dev/null || true)"
if [[ -z "$HOOKS_DIR" ]]; then
    HOOKS_DIR="$(git -C "$REPO_DIR" rev-parse --git-path hooks 2>/dev/null || true)"
fi
if [[ -z "$HOOKS_DIR" ]]; then
    echo "Could not determine git hooks directory for $REPO_DIR" >&2
    exit 1
fi
[[ "$HOOKS_DIR" != /* ]] && HOOKS_DIR="$REPO_DIR/$HOOKS_DIR"

HOOK_FILE="$HOOKS_DIR/prepare-commit-msg"
PRESERVED="$HOOKS_DIR/prepare-commit-msg.glean-preserved"

mkdir -p "$HOOKS_DIR"

if [[ -f "$HOOK_FILE" ]] && grep -q "Glean Code Writer branding wrapper" "$HOOK_FILE" 2>/dev/null; then
    exit 0
fi

[[ -f "$HOOK_FILE" ]] && mv "$HOOK_FILE" "$PRESERVED"

cat > "$HOOK_FILE" <<'EOF'
#!/bin/bash
# Glean Code Writer branding wrapper
set -euo pipefail

# Run preserved hook first
PRESERVED="$(dirname "$0")/prepare-commit-msg.glean-preserved"
[[ -x "$PRESERVED" ]] && { "$PRESERVED" "$@" || exit $?; }

if [[ -z "${2:-}" || "$2" == "message" ]]; then
    grep -q "Generated by Glean Code Writer" "$1" 2>/dev/null || printf '\nGenerated by Glean Code Writer\n' >> "$1"
fi
EOF

chmod +x "$HOOK_FILE"
