#!/bin/bash
# PR Creation PreToolUse Hook
# Intercepts gh api PR creation commands and ensures Glean template is used
#
# ============================================================================
# COMMAND DETECTION PATTERNS
# ============================================================================
# We detect PR creation by checking for BOTH:
#   1. "gh api" command
#   2. URL contains "/pulls" (not "/pulls/" which would be a specific PR)
#   3. POST method indicator
#
# POST method variations we catch:
#   --method POST, --method=POST, -X POST, -XPOST, -X=POST
#
# LIMITATIONS (inherent to textual command analysis):
#   - Variables: METHOD=POST; gh api --method $METHOD  (not detected)
#   - Subshells: $(echo POST)
#   - Commands built dynamically
#
# This hook is BEST-EFFORT. The Stop hook is the authoritative safety net
# that checks the actual PR state before session completion.
#
# ============================================================================
# VALIDATION LOGIC
# ============================================================================
# When a PR creation command is detected, we check if either:
#   1. The command references our Glean template file: pull_request_template_glean_code_writer.md
#   2. The command body already contains our marker: "Generated by Glean Code Writer"
#
# If neither is true, we block and instruct Claude to use the Glean template.
# ============================================================================

set -euo pipefail

# Read the JSON input from stdin
# Format: { "tool_name": "Bash", "tool_input": { "command": "..." } }
input=$(cat)

# Extract tool name
tool_name=$(echo "$input" | jq -r '.tool_name // ""')

# Only process Bash tool calls
if [[ "$tool_name" != "Bash" ]]; then
  exit 0
fi

# Get the command being executed
command=$(echo "$input" | jq -r '.tool_input.command // ""')
# Normalize command for case-insensitive detection (keep original for messaging)
command_lower=$(printf '%s' "$command" | tr '[:upper:]' '[:lower:]')

# Detect PR creation: "gh api" + "/pulls" endpoint + POST method
#
# We check:
#   1. Command contains "gh" and "api"
#   2. URL ends with "/pulls" (not "/pulls/123" which is a specific PR)
#   3. Contains POST method flag (various formats)
#
# POST method patterns (case-insensitive):
#   --method POST, --method=POST, -X POST, -XPOST, -X=POST
is_pr_creation=false

# Must have gh api and /pulls endpoint (not /pulls/ with a number)
if [[ "$command_lower" =~ gh[[:space:]]+api([[:space:]]|$) ]] && \
   [[ "$command_lower" =~ /pulls([[:space:]]|$|\") ]] && \
   [[ ! "$command_lower" =~ /pulls/[0-9] ]]; then

  # Check for POST method (various formats)
  if [[ "$command_lower" =~ --method[=[:space:]]*post ]] || \
     [[ "$command_lower" =~ -x[=[:space:]]*post ]] || \
     [[ "$command_lower" =~ -xpost ]]; then
    is_pr_creation=true
  fi
fi

if [[ "$is_pr_creation" == "true" ]]; then
  REPO_DIR="${REPO_DIR:-/workspace/repo}"
  SNAPSHOT_FILE="/opt/claude-hooks/remote-branches-snapshot"
  if [[ -f /opt/claude-hooks/branch-guard.sh ]]; then
    source /opt/claude-hooks/branch-guard.sh
  fi
  if command -v ensure_branch_ok >/dev/null 2>&1; then
    if ! ensure_branch_ok "$REPO_DIR" "$SNAPSHOT_FILE"; then
      print_branch_guard_block "create PR" && exit 0
    fi
  fi
  GLEAN_TEMPLATE="/workspace/tmp/pull_request_template_glean_code_writer.md"
  PR_TEMPLATE_MARKER="Generated by Glean Code Writer"

  # Check if the command uses our Glean template or already has the marker
  uses_template=false
  if [[ "$command" == *"$GLEAN_TEMPLATE"* ]]; then
    uses_template=true
  elif [[ "$command" == *"$PR_TEMPLATE_MARKER"* ]]; then
    uses_template=true
  fi

  if [[ "$uses_template" == "false" ]]; then
    cat >&2 <<EOF
❌ Cannot create PR: must use PR template

When creating a PR, you must use the template.

WORKFLOW:
1. First, edit the template to fill in your PR description:
   - Read it: cat $GLEAN_TEMPLATE
   - Modify it with your actual description (keep the branding footer!)

2. Then create the PR using the template file:
   gh api repos/{owner}/{repo}/pulls \\
     --method POST \\
     -f title="Your PR Title" \\
     -f head="your-branch" \\
     -f base="main" \\
     -F draft=true \\
     -f body="\$(cat $GLEAN_TEMPLATE)"

EOF
    echo '{"decision":"block","reason":"PR creation must use the template. Edit '"$GLEAN_TEMPLATE"' with your description, then use: -f body=\"$(cat '"$GLEAN_TEMPLATE"')\""}'
    exit 0
  fi
fi

# Allow all other commands
exit 0
