linters:
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck

issues:
  exclude-dirs:
    - api/proto/runner
  max-issues-per-linter: 0
  max-same-issues: 0
