// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Runner states
type RunnerState int32

const (
	RunnerState_RUNNER_STATE_UNSPECIFIED  RunnerState = 0
	RunnerState_RUNNER_STATE_COLD         RunnerState = 1
	RunnerState_RUNNER_STATE_BOOTING      RunnerState = 2
	RunnerState_RUNNER_STATE_INITIALIZING RunnerState = 3
	RunnerState_RUNNER_STATE_IDLE         RunnerState = 4
	RunnerState_RUNNER_STATE_BUSY         RunnerState = 5
	RunnerState_RUNNER_STATE_DRAINING     RunnerState = 6
	RunnerState_RUNNER_STATE_QUARANTINED  RunnerState = 7
	RunnerState_RUNNER_STATE_RETIRING     RunnerState = 8
	RunnerState_RUNNER_STATE_TERMINATED   RunnerState = 9
	RunnerState_RUNNER_STATE_PAUSED       RunnerState = 10 // VM paused and pooled for reuse
	RunnerState_RUNNER_STATE_PAUSING      RunnerState = 11 // snapshot in progress
	RunnerState_RUNNER_STATE_SUSPENDED    RunnerState = 12 // VM destroyed, session snapshot exists
)

// Enum value maps for RunnerState.
var (
	RunnerState_name = map[int32]string{
		0:  "RUNNER_STATE_UNSPECIFIED",
		1:  "RUNNER_STATE_COLD",
		2:  "RUNNER_STATE_BOOTING",
		3:  "RUNNER_STATE_INITIALIZING",
		4:  "RUNNER_STATE_IDLE",
		5:  "RUNNER_STATE_BUSY",
		6:  "RUNNER_STATE_DRAINING",
		7:  "RUNNER_STATE_QUARANTINED",
		8:  "RUNNER_STATE_RETIRING",
		9:  "RUNNER_STATE_TERMINATED",
		10: "RUNNER_STATE_PAUSED",
		11: "RUNNER_STATE_PAUSING",
		12: "RUNNER_STATE_SUSPENDED",
	}
	RunnerState_value = map[string]int32{
		"RUNNER_STATE_UNSPECIFIED":  0,
		"RUNNER_STATE_COLD":         1,
		"RUNNER_STATE_BOOTING":      2,
		"RUNNER_STATE_INITIALIZING": 3,
		"RUNNER_STATE_IDLE":         4,
		"RUNNER_STATE_BUSY":         5,
		"RUNNER_STATE_DRAINING":     6,
		"RUNNER_STATE_QUARANTINED":  7,
		"RUNNER_STATE_RETIRING":     8,
		"RUNNER_STATE_TERMINATED":   9,
		"RUNNER_STATE_PAUSED":       10,
		"RUNNER_STATE_PAUSING":      11,
		"RUNNER_STATE_SUSPENDED":    12,
	}
)

func (x RunnerState) Enum() *RunnerState {
	p := new(RunnerState)
	*p = x
	return p
}

func (x RunnerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunnerState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_runner_proto_enumTypes[0].Descriptor()
}

func (RunnerState) Type() protoreflect.EnumType {
	return &file_api_proto_runner_proto_enumTypes[0]
}

func (x RunnerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunnerState.Descriptor instead.
func (RunnerState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{0}
}

// Host states
type HostState int32

const (
	HostState_HOST_STATE_UNSPECIFIED HostState = 0
	HostState_HOST_STATE_STARTING    HostState = 1
	HostState_HOST_STATE_READY       HostState = 2
	HostState_HOST_STATE_DRAINING    HostState = 3
	HostState_HOST_STATE_UNHEALTHY   HostState = 4
)

// Enum value maps for HostState.
var (
	HostState_name = map[int32]string{
		0: "HOST_STATE_UNSPECIFIED",
		1: "HOST_STATE_STARTING",
		2: "HOST_STATE_READY",
		3: "HOST_STATE_DRAINING",
		4: "HOST_STATE_UNHEALTHY",
	}
	HostState_value = map[string]int32{
		"HOST_STATE_UNSPECIFIED": 0,
		"HOST_STATE_STARTING":    1,
		"HOST_STATE_READY":       2,
		"HOST_STATE_DRAINING":    3,
		"HOST_STATE_UNHEALTHY":   4,
	}
)

func (x HostState) Enum() *HostState {
	p := new(HostState)
	*p = x
	return p
}

func (x HostState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_runner_proto_enumTypes[1].Descriptor()
}

func (HostState) Type() protoreflect.EnumType {
	return &file_api_proto_runner_proto_enumTypes[1]
}

func (x HostState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostState.Descriptor instead.
func (HostState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{1}
}

// Resources requested for a runner
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpus         int32                  `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        int32                  `protobuf:"varint,3,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_api_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{0}
}

func (x *Resources) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *Resources) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Resources) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

// Runner represents a single runner instance
type Runner struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId          string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	State           RunnerState            `protobuf:"varint,3,opt,name=state,proto3,enum=runner.RunnerState" json:"state,omitempty"`
	InternalIp      string                 `protobuf:"bytes,4,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	JobId           string                 `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SnapshotVersion string                 `protobuf:"bytes,7,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Resources       *Resources             `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_api_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runner.ProtoReflect.Descriptor instead.
func (*Runner) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *Runner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Runner) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Runner) GetState() RunnerState {
	if x != nil {
		return x.State
	}
	return RunnerState_RUNNER_STATE_UNSPECIFIED
}

func (x *Runner) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *Runner) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Runner) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *Runner) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Runner) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Runner) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

// HostStatus represents the current status of a host
type HostStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostId           string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	InstanceName     string                 `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Zone             string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	State            HostState              `protobuf:"varint,4,opt,name=state,proto3,enum=runner.HostState" json:"state,omitempty"`
	TotalSlots       int32                  `protobuf:"varint,5,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	UsedSlots        int32                  `protobuf:"varint,6,opt,name=used_slots,json=usedSlots,proto3" json:"used_slots,omitempty"`
	IdleRunners      int32                  `protobuf:"varint,7,opt,name=idle_runners,json=idleRunners,proto3" json:"idle_runners,omitempty"`
	BusyRunners      int32                  `protobuf:"varint,8,opt,name=busy_runners,json=busyRunners,proto3" json:"busy_runners,omitempty"`
	CpuUsage         float64                `protobuf:"fixed64,9,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage      float64                `protobuf:"fixed64,10,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage        float64                `protobuf:"fixed64,11,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	SnapshotVersion  string                 `protobuf:"bytes,12,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	SnapshotSyncedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=snapshot_synced_at,json=snapshotSyncedAt,proto3" json:"snapshot_synced_at,omitempty"`
	LastHeartbeat    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// Pool statistics
	PoolStats     *PoolStats `protobuf:"bytes,15,opt,name=pool_stats,json=poolStats,proto3" json:"pool_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatus) Reset() {
	*x = HostStatus{}
	mi := &file_api_proto_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatus) ProtoMessage() {}

func (x *HostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatus.ProtoReflect.Descriptor instead.
func (*HostStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{2}
}

func (x *HostStatus) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostStatus) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *HostStatus) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *HostStatus) GetState() HostState {
	if x != nil {
		return x.State
	}
	return HostState_HOST_STATE_UNSPECIFIED
}

func (x *HostStatus) GetTotalSlots() int32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *HostStatus) GetUsedSlots() int32 {
	if x != nil {
		return x.UsedSlots
	}
	return 0
}

func (x *HostStatus) GetIdleRunners() int32 {
	if x != nil {
		return x.IdleRunners
	}
	return 0
}

func (x *HostStatus) GetBusyRunners() int32 {
	if x != nil {
		return x.BusyRunners
	}
	return 0
}

func (x *HostStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HostStatus) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HostStatus) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *HostStatus) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *HostStatus) GetSnapshotSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotSyncedAt
	}
	return nil
}

func (x *HostStatus) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *HostStatus) GetPoolStats() *PoolStats {
	if x != nil {
		return x.PoolStats
	}
	return nil
}

// PoolStats contains runner pool statistics
type PoolStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PooledRunners    int32                  `protobuf:"varint,1,opt,name=pooled_runners,json=pooledRunners,proto3" json:"pooled_runners,omitempty"`
	MaxRunners       int32                  `protobuf:"varint,2,opt,name=max_runners,json=maxRunners,proto3" json:"max_runners,omitempty"`
	MemoryUsageBytes int64                  `protobuf:"varint,3,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MaxMemoryBytes   int64                  `protobuf:"varint,4,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	PoolHits         int64                  `protobuf:"varint,5,opt,name=pool_hits,json=poolHits,proto3" json:"pool_hits,omitempty"`
	PoolMisses       int64                  `protobuf:"varint,6,opt,name=pool_misses,json=poolMisses,proto3" json:"pool_misses,omitempty"`
	Evictions        int64                  `protobuf:"varint,7,opt,name=evictions,proto3" json:"evictions,omitempty"`
	RecycleFailures  int64                  `protobuf:"varint,8,opt,name=recycle_failures,json=recycleFailures,proto3" json:"recycle_failures,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PoolStats) Reset() {
	*x = PoolStats{}
	mi := &file_api_proto_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStats) ProtoMessage() {}

func (x *PoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStats.ProtoReflect.Descriptor instead.
func (*PoolStats) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{3}
}

func (x *PoolStats) GetPooledRunners() int32 {
	if x != nil {
		return x.PooledRunners
	}
	return 0
}

func (x *PoolStats) GetMaxRunners() int32 {
	if x != nil {
		return x.MaxRunners
	}
	return 0
}

func (x *PoolStats) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *PoolStats) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *PoolStats) GetPoolHits() int64 {
	if x != nil {
		return x.PoolHits
	}
	return 0
}

func (x *PoolStats) GetPoolMisses() int64 {
	if x != nil {
		return x.PoolMisses
	}
	return 0
}

func (x *PoolStats) GetEvictions() int64 {
	if x != nil {
		return x.Evictions
	}
	return 0
}

func (x *PoolStats) GetRecycleFailures() int64 {
	if x != nil {
		return x.RecycleFailures
	}
	return 0
}

// Snapshot represents a snapshot version
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	GcsPath       string                 `protobuf:"bytes,3,opt,name=gcs_path,json=gcsPath,proto3" json:"gcs_path,omitempty"`
	RepoCommit    string                 `protobuf:"bytes,5,opt,name=repo_commit,json=repoCommit,proto3" json:"repo_commit,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_proto_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{4}
}

func (x *Snapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Snapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Snapshot) GetGcsPath() string {
	if x != nil {
		return x.GcsPath
	}
	return ""
}

func (x *Snapshot) GetRepoCommit() string {
	if x != nil {
		return x.RepoCommit
	}
	return ""
}

func (x *Snapshot) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Snapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// StartCommand defines an arbitrary workload to run inside the VM. This is the
// primary workload model — the VM starts this process and exposes it on the
// specified port.
type StartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	HealthPath    string                 `protobuf:"bytes,3,opt,name=health_path,json=healthPath,proto3" json:"health_path,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RunAs         string                 `protobuf:"bytes,5,opt,name=run_as,json=runAs,proto3" json:"run_as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCommand) Reset() {
	*x = StartCommand{}
	mi := &file_api_proto_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCommand) ProtoMessage() {}

func (x *StartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCommand.ProtoReflect.Descriptor instead.
func (*StartCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{5}
}

func (x *StartCommand) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartCommand) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartCommand) GetHealthPath() string {
	if x != nil {
		return x.HealthPath
	}
	return ""
}

func (x *StartCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartCommand) GetRunAs() string {
	if x != nil {
		return x.RunAs
	}
	return ""
}

// AllocateRunnerRequest
type AllocateRunnerRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	RequestId                    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Resources                    *Resources             `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Labels                       map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkloadKey                  string                 `protobuf:"bytes,10,opt,name=workload_key,json=workloadKey,proto3" json:"workload_key,omitempty"`                                                         // Hash of snapshot commands; identifies which snapshot to boot
	StartCommand                 *StartCommand          `protobuf:"bytes,11,opt,name=start_command,json=startCommand,proto3" json:"start_command,omitempty"`                                                      // Optional: user service to start inside the VM
	SessionId                    string                 `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                               // optional: bind to session for pause/resume
	SnapshotVersion              string                 `protobuf:"bytes,13,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`                                             // Explicit version to use; skips current-pointer.json lookup
	TtlSeconds                   int32                  `protobuf:"varint,14,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                                                           // idle timeout from snapshot config (0 = no timeout)
	AutoPause                    bool                   `protobuf:"varint,15,opt,name=auto_pause,json=autoPause,proto3" json:"auto_pause,omitempty"`                                                              // pause on TTL expiry instead of destroy
	SnapshotTag                  string                 `protobuf:"bytes,16,opt,name=snapshot_tag,json=snapshotTag,proto3" json:"snapshot_tag,omitempty"`                                                         // optional: named tag to resolve snapshot version
	NetworkPolicyPreset          string                 `protobuf:"bytes,17,opt,name=network_policy_preset,json=networkPolicyPreset,proto3" json:"network_policy_preset,omitempty"`                               // optional: named preset (e.g., "restricted-egress", "agent-sandbox")
	NetworkPolicyJson            string                 `protobuf:"bytes,18,opt,name=network_policy_json,json=networkPolicyJson,proto3" json:"network_policy_json,omitempty"`                                     // optional: full NetworkPolicy as JSON (overrides preset)
	CheckpointIntervalSeconds    int32                  `protobuf:"varint,19,opt,name=checkpoint_interval_seconds,json=checkpointIntervalSeconds,proto3" json:"checkpoint_interval_seconds,omitempty"`            // periodic checkpoint cadence for long-lived sessions (0 = disabled)
	CheckpointQuietWindowSeconds int32                  `protobuf:"varint,20,opt,name=checkpoint_quiet_window_seconds,json=checkpointQuietWindowSeconds,proto3" json:"checkpoint_quiet_window_seconds,omitempty"` // minimum quiet time before periodic checkpoints
	ResumeManifestPath           string                 `protobuf:"bytes,21,opt,name=resume_manifest_path,json=resumeManifestPath,proto3" json:"resume_manifest_path,omitempty"`                                  // authoritative session head manifest for cross-host resume
	SessionGeneration            int32                  `protobuf:"varint,22,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`                                      // authoritative session generation for cross-host resume
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AllocateRunnerRequest) Reset() {
	*x = AllocateRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRunnerRequest) ProtoMessage() {}

func (x *AllocateRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRunnerRequest.ProtoReflect.Descriptor instead.
func (*AllocateRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateRunnerRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AllocateRunnerRequest) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AllocateRunnerRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AllocateRunnerRequest) GetWorkloadKey() string {
	if x != nil {
		return x.WorkloadKey
	}
	return ""
}

func (x *AllocateRunnerRequest) GetStartCommand() *StartCommand {
	if x != nil {
		return x.StartCommand
	}
	return nil
}

func (x *AllocateRunnerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AllocateRunnerRequest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *AllocateRunnerRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *AllocateRunnerRequest) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *AllocateRunnerRequest) GetSnapshotTag() string {
	if x != nil {
		return x.SnapshotTag
	}
	return ""
}

func (x *AllocateRunnerRequest) GetNetworkPolicyPreset() string {
	if x != nil {
		return x.NetworkPolicyPreset
	}
	return ""
}

func (x *AllocateRunnerRequest) GetNetworkPolicyJson() string {
	if x != nil {
		return x.NetworkPolicyJson
	}
	return ""
}

func (x *AllocateRunnerRequest) GetCheckpointIntervalSeconds() int32 {
	if x != nil {
		return x.CheckpointIntervalSeconds
	}
	return 0
}

func (x *AllocateRunnerRequest) GetCheckpointQuietWindowSeconds() int32 {
	if x != nil {
		return x.CheckpointQuietWindowSeconds
	}
	return 0
}

func (x *AllocateRunnerRequest) GetResumeManifestPath() string {
	if x != nil {
		return x.ResumeManifestPath
	}
	return ""
}

func (x *AllocateRunnerRequest) GetSessionGeneration() int32 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

// AllocateRunnerResponse
type AllocateRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Resumed       bool                   `protobuf:"varint,3,opt,name=resumed,proto3" json:"resumed,omitempty"`                     // true if restored from session snapshot
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // session_id (echoed back or generated)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRunnerResponse) Reset() {
	*x = AllocateRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRunnerResponse) ProtoMessage() {}

func (x *AllocateRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRunnerResponse.ProtoReflect.Descriptor instead.
func (*AllocateRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{7}
}

func (x *AllocateRunnerResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

func (x *AllocateRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AllocateRunnerResponse) GetResumed() bool {
	if x != nil {
		return x.Resumed
	}
	return false
}

func (x *AllocateRunnerResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ReleaseRunnerRequest
type ReleaseRunnerRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunnerId string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Destroy  bool                   `protobuf:"varint,2,opt,name=destroy,proto3" json:"destroy,omitempty"`
	// try_recycle attempts to pause and pool the runner for reuse
	// Only works if pool is enabled and finished_cleanly is true
	TryRecycle bool `protobuf:"varint,3,opt,name=try_recycle,json=tryRecycle,proto3" json:"try_recycle,omitempty"`
	// finished_cleanly indicates the task completed without errors
	// Required for try_recycle to succeed
	FinishedCleanly bool `protobuf:"varint,4,opt,name=finished_cleanly,json=finishedCleanly,proto3" json:"finished_cleanly,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReleaseRunnerRequest) Reset() {
	*x = ReleaseRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRunnerRequest) ProtoMessage() {}

func (x *ReleaseRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRunnerRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseRunnerRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ReleaseRunnerRequest) GetDestroy() bool {
	if x != nil {
		return x.Destroy
	}
	return false
}

func (x *ReleaseRunnerRequest) GetTryRecycle() bool {
	if x != nil {
		return x.TryRecycle
	}
	return false
}

func (x *ReleaseRunnerRequest) GetFinishedCleanly() bool {
	if x != nil {
		return x.FinishedCleanly
	}
	return false
}

// ReleaseRunnerResponse
type ReleaseRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRunnerResponse) Reset() {
	*x = ReleaseRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRunnerResponse) ProtoMessage() {}

func (x *ReleaseRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRunnerResponse.ProtoReflect.Descriptor instead.
func (*ReleaseRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseRunnerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetHostStatusRequest
type GetHostStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostStatusRequest) Reset() {
	*x = GetHostStatusRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostStatusRequest) ProtoMessage() {}

func (x *GetHostStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostStatusRequest.ProtoReflect.Descriptor instead.
func (*GetHostStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{10}
}

// HeartbeatRequest
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Status        *HostStatus            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *HostStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// HeartbeatResponse
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ShouldDrain   bool                   `protobuf:"varint,4,opt,name=should_drain,json=shouldDrain,proto3" json:"should_drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetShouldDrain() bool {
	if x != nil {
		return x.ShouldDrain
	}
	return false
}

// ListRunnersRequest
type ListRunnersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateFilter   RunnerState            `protobuf:"varint,1,opt,name=state_filter,json=stateFilter,proto3,enum=runner.RunnerState" json:"state_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunnersRequest) Reset() {
	*x = ListRunnersRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnersRequest) ProtoMessage() {}

func (x *ListRunnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnersRequest.ProtoReflect.Descriptor instead.
func (*ListRunnersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{13}
}

func (x *ListRunnersRequest) GetStateFilter() RunnerState {
	if x != nil {
		return x.StateFilter
	}
	return RunnerState_RUNNER_STATE_UNSPECIFIED
}

// ListRunnersResponse
type ListRunnersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runners       []*Runner              `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunnersResponse) Reset() {
	*x = ListRunnersResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnersResponse) ProtoMessage() {}

func (x *ListRunnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnersResponse.ProtoReflect.Descriptor instead.
func (*ListRunnersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{14}
}

func (x *ListRunnersResponse) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

// GetRunnerRequest
type GetRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnerRequest) Reset() {
	*x = GetRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerRequest) ProtoMessage() {}

func (x *GetRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerRequest.ProtoReflect.Descriptor instead.
func (*GetRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{15}
}

func (x *GetRunnerRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

// GetRunnerResponse
type GetRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	HostAddress   string                 `protobuf:"bytes,2,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnerResponse) Reset() {
	*x = GetRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerResponse) ProtoMessage() {}

func (x *GetRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerResponse.ProtoReflect.Descriptor instead.
func (*GetRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{16}
}

func (x *GetRunnerResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

func (x *GetRunnerResponse) GetHostAddress() string {
	if x != nil {
		return x.HostAddress
	}
	return ""
}

func (x *GetRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QuarantineRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	BlockEgress   bool                   `protobuf:"varint,3,opt,name=block_egress,json=blockEgress,proto3" json:"block_egress,omitempty"`
	PauseVm       bool                   `protobuf:"varint,4,opt,name=pause_vm,json=pauseVm,proto3" json:"pause_vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuarantineRunnerRequest) Reset() {
	*x = QuarantineRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuarantineRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuarantineRunnerRequest) ProtoMessage() {}

func (x *QuarantineRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuarantineRunnerRequest.ProtoReflect.Descriptor instead.
func (*QuarantineRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{17}
}

func (x *QuarantineRunnerRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *QuarantineRunnerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *QuarantineRunnerRequest) GetBlockEgress() bool {
	if x != nil {
		return x.BlockEgress
	}
	return false
}

func (x *QuarantineRunnerRequest) GetPauseVm() bool {
	if x != nil {
		return x.PauseVm
	}
	return false
}

type QuarantineRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	QuarantineDir string                 `protobuf:"bytes,3,opt,name=quarantine_dir,json=quarantineDir,proto3" json:"quarantine_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuarantineRunnerResponse) Reset() {
	*x = QuarantineRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuarantineRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuarantineRunnerResponse) ProtoMessage() {}

func (x *QuarantineRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuarantineRunnerResponse.ProtoReflect.Descriptor instead.
func (*QuarantineRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{18}
}

func (x *QuarantineRunnerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QuarantineRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QuarantineRunnerResponse) GetQuarantineDir() string {
	if x != nil {
		return x.QuarantineDir
	}
	return ""
}

type UnquarantineRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	UnblockEgress bool                   `protobuf:"varint,2,opt,name=unblock_egress,json=unblockEgress,proto3" json:"unblock_egress,omitempty"`
	ResumeVm      bool                   `protobuf:"varint,3,opt,name=resume_vm,json=resumeVm,proto3" json:"resume_vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnquarantineRunnerRequest) Reset() {
	*x = UnquarantineRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnquarantineRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnquarantineRunnerRequest) ProtoMessage() {}

func (x *UnquarantineRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnquarantineRunnerRequest.ProtoReflect.Descriptor instead.
func (*UnquarantineRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{19}
}

func (x *UnquarantineRunnerRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *UnquarantineRunnerRequest) GetUnblockEgress() bool {
	if x != nil {
		return x.UnblockEgress
	}
	return false
}

func (x *UnquarantineRunnerRequest) GetResumeVm() bool {
	if x != nil {
		return x.ResumeVm
	}
	return false
}

type UnquarantineRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnquarantineRunnerResponse) Reset() {
	*x = UnquarantineRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnquarantineRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnquarantineRunnerResponse) ProtoMessage() {}

func (x *UnquarantineRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnquarantineRunnerResponse.ProtoReflect.Descriptor instead.
func (*UnquarantineRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{20}
}

func (x *UnquarantineRunnerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnquarantineRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RegisterHostRequest
type RegisterHostRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceName    string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Zone            string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	TotalSlots      int32                  `protobuf:"varint,3,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	SnapshotVersion string                 `protobuf:"bytes,4,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterHostRequest) Reset() {
	*x = RegisterHostRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostRequest) ProtoMessage() {}

func (x *RegisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostRequest.ProtoReflect.Descriptor instead.
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterHostRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *RegisterHostRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *RegisterHostRequest) GetTotalSlots() int32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *RegisterHostRequest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

// RegisterHostResponse
type RegisterHostResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	SnapshotVersion string                 `protobuf:"bytes,2,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterHostResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterHostResponse) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

// GetSnapshotRequest
type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{23}
}

func (x *GetSnapshotRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// TriggerSnapshotBuildRequest (deprecated — fields reserved)
type TriggerSnapshotBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotBuildRequest) Reset() {
	*x = TriggerSnapshotBuildRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotBuildRequest) ProtoMessage() {}

func (x *TriggerSnapshotBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotBuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotBuildRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{24}
}

// TriggerSnapshotBuildResponse (deprecated — fields reserved)
type TriggerSnapshotBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotBuildResponse) Reset() {
	*x = TriggerSnapshotBuildResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotBuildResponse) ProtoMessage() {}

func (x *TriggerSnapshotBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotBuildResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotBuildResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{25}
}

type PauseRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunnerRequest) Reset() {
	*x = PauseRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunnerRequest) ProtoMessage() {}

func (x *PauseRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunnerRequest.ProtoReflect.Descriptor instead.
func (*PauseRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{26}
}

func (x *PauseRunnerRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type PauseRunnerResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error             string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SessionId         string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SnapshotSizeBytes int64                  `protobuf:"varint,4,opt,name=snapshot_size_bytes,json=snapshotSizeBytes,proto3" json:"snapshot_size_bytes,omitempty"`
	Layer             int32                  `protobuf:"varint,5,opt,name=layer,proto3" json:"layer,omitempty"`
	Generation        int32                  `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	ManifestPath      string                 `protobuf:"bytes,7,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PauseRunnerResponse) Reset() {
	*x = PauseRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunnerResponse) ProtoMessage() {}

func (x *PauseRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunnerResponse.ProtoReflect.Descriptor instead.
func (*PauseRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{27}
}

func (x *PauseRunnerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PauseRunnerResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PauseRunnerResponse) GetSnapshotSizeBytes() int64 {
	if x != nil {
		return x.SnapshotSizeBytes
	}
	return 0
}

func (x *PauseRunnerResponse) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *PauseRunnerResponse) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PauseRunnerResponse) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

type ResumeRunnerRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	SessionId                    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkloadKey                  string                 `protobuf:"bytes,2,opt,name=workload_key,json=workloadKey,proto3" json:"workload_key,omitempty"`
	TtlSeconds                   int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	AutoPause                    bool                   `protobuf:"varint,4,opt,name=auto_pause,json=autoPause,proto3" json:"auto_pause,omitempty"`
	NetworkPolicyPreset          string                 `protobuf:"bytes,5,opt,name=network_policy_preset,json=networkPolicyPreset,proto3" json:"network_policy_preset,omitempty"`
	NetworkPolicyJson            string                 `protobuf:"bytes,6,opt,name=network_policy_json,json=networkPolicyJson,proto3" json:"network_policy_json,omitempty"`
	ManifestPath                 string                 `protobuf:"bytes,7,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	Generation                   int32                  `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	CheckpointIntervalSeconds    int32                  `protobuf:"varint,9,opt,name=checkpoint_interval_seconds,json=checkpointIntervalSeconds,proto3" json:"checkpoint_interval_seconds,omitempty"`
	CheckpointQuietWindowSeconds int32                  `protobuf:"varint,10,opt,name=checkpoint_quiet_window_seconds,json=checkpointQuietWindowSeconds,proto3" json:"checkpoint_quiet_window_seconds,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ResumeRunnerRequest) Reset() {
	*x = ResumeRunnerRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunnerRequest) ProtoMessage() {}

func (x *ResumeRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunnerRequest.ProtoReflect.Descriptor instead.
func (*ResumeRunnerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{28}
}

func (x *ResumeRunnerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeRunnerRequest) GetWorkloadKey() string {
	if x != nil {
		return x.WorkloadKey
	}
	return ""
}

func (x *ResumeRunnerRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ResumeRunnerRequest) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *ResumeRunnerRequest) GetNetworkPolicyPreset() string {
	if x != nil {
		return x.NetworkPolicyPreset
	}
	return ""
}

func (x *ResumeRunnerRequest) GetNetworkPolicyJson() string {
	if x != nil {
		return x.NetworkPolicyJson
	}
	return ""
}

func (x *ResumeRunnerRequest) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

func (x *ResumeRunnerRequest) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ResumeRunnerRequest) GetCheckpointIntervalSeconds() int32 {
	if x != nil {
		return x.CheckpointIntervalSeconds
	}
	return 0
}

func (x *ResumeRunnerRequest) GetCheckpointQuietWindowSeconds() int32 {
	if x != nil {
		return x.CheckpointQuietWindowSeconds
	}
	return 0
}

type ResumeRunnerResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Runner             *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	Error              string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ResumedFromSession bool                   `protobuf:"varint,3,opt,name=resumed_from_session,json=resumedFromSession,proto3" json:"resumed_from_session,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResumeRunnerResponse) Reset() {
	*x = ResumeRunnerResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunnerResponse) ProtoMessage() {}

func (x *ResumeRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunnerResponse.ProtoReflect.Descriptor instead.
func (*ResumeRunnerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{29}
}

func (x *ResumeRunnerResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

func (x *ResumeRunnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResumeRunnerResponse) GetResumedFromSession() bool {
	if x != nil {
		return x.ResumedFromSession
	}
	return false
}

type UpdateNetworkPolicyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunnerId          string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	NetworkPolicyJson string                 `protobuf:"bytes,2,opt,name=network_policy_json,json=networkPolicyJson,proto3" json:"network_policy_json,omitempty"` // Full NetworkPolicy as JSON (full replace)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateNetworkPolicyRequest) Reset() {
	*x = UpdateNetworkPolicyRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkPolicyRequest) ProtoMessage() {}

func (x *UpdateNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateNetworkPolicyRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *UpdateNetworkPolicyRequest) GetNetworkPolicyJson() string {
	if x != nil {
		return x.NetworkPolicyJson
	}
	return ""
}

type UpdateNetworkPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNetworkPolicyResponse) Reset() {
	*x = UpdateNetworkPolicyResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkPolicyResponse) ProtoMessage() {}

func (x *UpdateNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateNetworkPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateNetworkPolicyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateNetworkPolicyResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkPolicyRequest) Reset() {
	*x = GetNetworkPolicyRequest{}
	mi := &file_api_proto_runner_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkPolicyRequest) ProtoMessage() {}

func (x *GetNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{32}
}

func (x *GetNetworkPolicyRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type GetNetworkPolicyResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NetworkPolicyJson      string                 `protobuf:"bytes,1,opt,name=network_policy_json,json=networkPolicyJson,proto3" json:"network_policy_json,omitempty"` // Effective policy as JSON
	Version                int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	EmergencyEgressBlocked bool                   `protobuf:"varint,3,opt,name=emergency_egress_blocked,json=emergencyEgressBlocked,proto3" json:"emergency_egress_blocked,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetNetworkPolicyResponse) Reset() {
	*x = GetNetworkPolicyResponse{}
	mi := &file_api_proto_runner_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkPolicyResponse) ProtoMessage() {}

func (x *GetNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_proto_rawDescGZIP(), []int{33}
}

func (x *GetNetworkPolicyResponse) GetNetworkPolicyJson() string {
	if x != nil {
		return x.NetworkPolicyJson
	}
	return ""
}

func (x *GetNetworkPolicyResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetNetworkPolicyResponse) GetEmergencyEgressBlocked() bool {
	if x != nil {
		return x.EmergencyEgressBlocked
	}
	return false
}

var File_api_proto_runner_proto protoreflect.FileDescriptor

const file_api_proto_runner_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/runner.proto\x12\x06runner\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\tResources\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x03 \x01(\x05R\x06diskGb\"\x80\x03\n" +
	"\x06Runner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.runner.RunnerStateR\x05state\x12\x1f\n" +
	"\vinternal_ip\x18\x04 \x01(\tR\n" +
	"internalIp\x12\x15\n" +
	"\x06job_id\x18\x06 \x01(\tR\x05jobId\x12)\n" +
	"\x10snapshot_version\x18\a \x01(\tR\x0fsnapshotVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12/\n" +
	"\tresources\x18\n" +
	" \x01(\v2\x11.runner.ResourcesR\tresourcesJ\x04\b\x05\x10\x06R\x12external_runner_id\"\xd6\x04\n" +
	"\n" +
	"HostStatus\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12'\n" +
	"\x05state\x18\x04 \x01(\x0e2\x11.runner.HostStateR\x05state\x12\x1f\n" +
	"\vtotal_slots\x18\x05 \x01(\x05R\n" +
	"totalSlots\x12\x1d\n" +
	"\n" +
	"used_slots\x18\x06 \x01(\x05R\tusedSlots\x12!\n" +
	"\fidle_runners\x18\a \x01(\x05R\vidleRunners\x12!\n" +
	"\fbusy_runners\x18\b \x01(\x05R\vbusyRunners\x12\x1b\n" +
	"\tcpu_usage\x18\t \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\n" +
	" \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\v \x01(\x01R\tdiskUsage\x12)\n" +
	"\x10snapshot_version\x18\f \x01(\tR\x0fsnapshotVersion\x12H\n" +
	"\x12snapshot_synced_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x10snapshotSyncedAt\x12A\n" +
	"\x0elast_heartbeat\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x120\n" +
	"\n" +
	"pool_stats\x18\x0f \x01(\v2\x11.runner.PoolStatsR\tpoolStats\"\xb2\x02\n" +
	"\tPoolStats\x12%\n" +
	"\x0epooled_runners\x18\x01 \x01(\x05R\rpooledRunners\x12\x1f\n" +
	"\vmax_runners\x18\x02 \x01(\x05R\n" +
	"maxRunners\x12,\n" +
	"\x12memory_usage_bytes\x18\x03 \x01(\x03R\x10memoryUsageBytes\x12(\n" +
	"\x10max_memory_bytes\x18\x04 \x01(\x03R\x0emaxMemoryBytes\x12\x1b\n" +
	"\tpool_hits\x18\x05 \x01(\x03R\bpoolHits\x12\x1f\n" +
	"\vpool_misses\x18\x06 \x01(\x03R\n" +
	"poolMisses\x12\x1c\n" +
	"\tevictions\x18\a \x01(\x03R\tevictions\x12)\n" +
	"\x10recycle_failures\x18\b \x01(\x03R\x0frecycleFailures\"\xec\x01\n" +
	"\bSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bgcs_path\x18\x03 \x01(\tR\agcsPath\x12\x1f\n" +
	"\vrepo_commit\x18\x05 \x01(\tR\n" +
	"repoCommit\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtJ\x04\b\x04\x10\x05R\x12build_tool_version\"\xdd\x01\n" +
	"\fStartCommand\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1f\n" +
	"\vhealth_path\x18\x03 \x01(\tR\n" +
	"healthPath\x12/\n" +
	"\x03env\x18\x04 \x03(\v2\x1d.runner.StartCommand.EnvEntryR\x03env\x12\x15\n" +
	"\x06run_as\x18\x05 \x01(\tR\x05runAs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\a\n" +
	"\x15AllocateRunnerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\tresources\x18\x05 \x01(\v2\x11.runner.ResourcesR\tresources\x12A\n" +
	"\x06labels\x18\x06 \x03(\v2).runner.AllocateRunnerRequest.LabelsEntryR\x06labels\x12!\n" +
	"\fworkload_key\x18\n" +
	" \x01(\tR\vworkloadKey\x129\n" +
	"\rstart_command\x18\v \x01(\v2\x14.runner.StartCommandR\fstartCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12)\n" +
	"\x10snapshot_version\x18\r \x01(\tR\x0fsnapshotVersion\x12\x1f\n" +
	"\vttl_seconds\x18\x0e \x01(\x05R\n" +
	"ttlSeconds\x12\x1d\n" +
	"\n" +
	"auto_pause\x18\x0f \x01(\bR\tautoPause\x12!\n" +
	"\fsnapshot_tag\x18\x10 \x01(\tR\vsnapshotTag\x122\n" +
	"\x15network_policy_preset\x18\x11 \x01(\tR\x13networkPolicyPreset\x12.\n" +
	"\x13network_policy_json\x18\x12 \x01(\tR\x11networkPolicyJson\x12>\n" +
	"\x1bcheckpoint_interval_seconds\x18\x13 \x01(\x05R\x19checkpointIntervalSeconds\x12E\n" +
	"\x1fcheckpoint_quiet_window_seconds\x18\x14 \x01(\x05R\x1ccheckpointQuietWindowSeconds\x120\n" +
	"\x14resume_manifest_path\x18\x15 \x01(\tR\x12resumeManifestPath\x12-\n" +
	"\x12session_generation\x18\x16 \x01(\x05R\x11sessionGeneration\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x04repoR\x06branchR\x06commitR\x13github_runner_tokenR\x0fci_runner_tokenR\x10integration_name\"\x8f\x01\n" +
	"\x16AllocateRunnerResponse\x12&\n" +
	"\x06runner\x18\x01 \x01(\v2\x0e.runner.RunnerR\x06runner\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aresumed\x18\x03 \x01(\bR\aresumed\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x99\x01\n" +
	"\x14ReleaseRunnerRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x18\n" +
	"\adestroy\x18\x02 \x01(\bR\adestroy\x12\x1f\n" +
	"\vtry_recycle\x18\x03 \x01(\bR\n" +
	"tryRecycle\x12)\n" +
	"\x10finished_cleanly\x18\x04 \x01(\bR\x0ffinishedCleanly\"G\n" +
	"\x15ReleaseRunnerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x16\n" +
	"\x14GetHostStatusRequest\"W\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.runner.HostStatusR\x06status\"\x8e\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12!\n" +
	"\fshould_drain\x18\x04 \x01(\bR\vshouldDrainJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x10snapshot_versionR\x14should_sync_snapshot\"L\n" +
	"\x12ListRunnersRequest\x126\n" +
	"\fstate_filter\x18\x01 \x01(\x0e2\x13.runner.RunnerStateR\vstateFilter\"?\n" +
	"\x13ListRunnersResponse\x12(\n" +
	"\arunners\x18\x01 \x03(\v2\x0e.runner.RunnerR\arunners\"/\n" +
	"\x10GetRunnerRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"t\n" +
	"\x11GetRunnerResponse\x12&\n" +
	"\x06runner\x18\x01 \x01(\v2\x0e.runner.RunnerR\x06runner\x12!\n" +
	"\fhost_address\x18\x02 \x01(\tR\vhostAddress\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8c\x01\n" +
	"\x17QuarantineRunnerRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fblock_egress\x18\x03 \x01(\bR\vblockEgress\x12\x19\n" +
	"\bpause_vm\x18\x04 \x01(\bR\apauseVm\"q\n" +
	"\x18QuarantineRunnerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0equarantine_dir\x18\x03 \x01(\tR\rquarantineDir\"|\n" +
	"\x19UnquarantineRunnerRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12%\n" +
	"\x0eunblock_egress\x18\x02 \x01(\bR\runblockEgress\x12\x1b\n" +
	"\tresume_vm\x18\x03 \x01(\bR\bresumeVm\"L\n" +
	"\x1aUnquarantineRunnerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9a\x01\n" +
	"\x13RegisterHostRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12\x1f\n" +
	"\vtotal_slots\x18\x03 \x01(\x05R\n" +
	"totalSlots\x12)\n" +
	"\x10snapshot_version\x18\x04 \x01(\tR\x0fsnapshotVersion\"Z\n" +
	"\x14RegisterHostResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12)\n" +
	"\x10snapshot_version\x18\x02 \x01(\tR\x0fsnapshotVersion\".\n" +
	"\x12GetSnapshotRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"Q\n" +
	"\x1bTriggerSnapshotBuildRequestJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x04repoR\x06branchR\x12build_tool_version\"<\n" +
	"\x1cTriggerSnapshotBuildResponseJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\bbuild_idR\x06status\"1\n" +
	"\x12PauseRunnerRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"\xef\x01\n" +
	"\x13PauseRunnerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12.\n" +
	"\x13snapshot_size_bytes\x18\x04 \x01(\x03R\x11snapshotSizeBytes\x12\x14\n" +
	"\x05layer\x18\x05 \x01(\x05R\x05layer\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x05R\n" +
	"generation\x12#\n" +
	"\rmanifest_path\x18\a \x01(\tR\fmanifestPath\"\xc7\x03\n" +
	"\x13ResumeRunnerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fworkload_key\x18\x02 \x01(\tR\vworkloadKey\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\x12\x1d\n" +
	"\n" +
	"auto_pause\x18\x04 \x01(\bR\tautoPause\x122\n" +
	"\x15network_policy_preset\x18\x05 \x01(\tR\x13networkPolicyPreset\x12.\n" +
	"\x13network_policy_json\x18\x06 \x01(\tR\x11networkPolicyJson\x12#\n" +
	"\rmanifest_path\x18\a \x01(\tR\fmanifestPath\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\x05R\n" +
	"generation\x12>\n" +
	"\x1bcheckpoint_interval_seconds\x18\t \x01(\x05R\x19checkpointIntervalSeconds\x12E\n" +
	"\x1fcheckpoint_quiet_window_seconds\x18\n" +
	" \x01(\x05R\x1ccheckpointQuietWindowSeconds\"\x86\x01\n" +
	"\x14ResumeRunnerResponse\x12&\n" +
	"\x06runner\x18\x01 \x01(\v2\x0e.runner.RunnerR\x06runner\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\x14resumed_from_session\x18\x03 \x01(\bR\x12resumedFromSession\"i\n" +
	"\x1aUpdateNetworkPolicyRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12.\n" +
	"\x13network_policy_json\x18\x02 \x01(\tR\x11networkPolicyJson\"g\n" +
	"\x1bUpdateNetworkPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"6\n" +
	"\x17GetNetworkPolicyRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"\x9e\x01\n" +
	"\x18GetNetworkPolicyResponse\x12.\n" +
	"\x13network_policy_json\x18\x01 \x01(\tR\x11networkPolicyJson\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x128\n" +
	"\x18emergency_egress_blocked\x18\x03 \x01(\bR\x16emergencyEgressBlocked*\xe9\x02\n" +
	"\vRunnerState\x12\x1c\n" +
	"\x18RUNNER_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RUNNER_STATE_COLD\x10\x01\x12\x18\n" +
	"\x14RUNNER_STATE_BOOTING\x10\x02\x12\x1d\n" +
	"\x19RUNNER_STATE_INITIALIZING\x10\x03\x12\x15\n" +
	"\x11RUNNER_STATE_IDLE\x10\x04\x12\x15\n" +
	"\x11RUNNER_STATE_BUSY\x10\x05\x12\x19\n" +
	"\x15RUNNER_STATE_DRAINING\x10\x06\x12\x1c\n" +
	"\x18RUNNER_STATE_QUARANTINED\x10\a\x12\x19\n" +
	"\x15RUNNER_STATE_RETIRING\x10\b\x12\x1b\n" +
	"\x17RUNNER_STATE_TERMINATED\x10\t\x12\x17\n" +
	"\x13RUNNER_STATE_PAUSED\x10\n" +
	"\x12\x18\n" +
	"\x14RUNNER_STATE_PAUSING\x10\v\x12\x1a\n" +
	"\x16RUNNER_STATE_SUSPENDED\x10\f*\x89\x01\n" +
	"\tHostState\x12\x1a\n" +
	"\x16HOST_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HOST_STATE_STARTING\x10\x01\x12\x14\n" +
	"\x10HOST_STATE_READY\x10\x02\x12\x17\n" +
	"\x13HOST_STATE_DRAINING\x10\x03\x12\x18\n" +
	"\x14HOST_STATE_UNHEALTHY\x10\x042\xac\a\n" +
	"\tHostAgent\x12O\n" +
	"\x0eAllocateRunner\x12\x1d.runner.AllocateRunnerRequest\x1a\x1e.runner.AllocateRunnerResponse\x12L\n" +
	"\rReleaseRunner\x12\x1c.runner.ReleaseRunnerRequest\x1a\x1d.runner.ReleaseRunnerResponse\x12A\n" +
	"\rGetHostStatus\x12\x1c.runner.GetHostStatusRequest\x1a\x12.runner.HostStatus\x12@\n" +
	"\tHeartbeat\x12\x18.runner.HeartbeatRequest\x1a\x19.runner.HeartbeatResponse\x12F\n" +
	"\vListRunners\x12\x1a.runner.ListRunnersRequest\x1a\x1b.runner.ListRunnersResponse\x125\n" +
	"\tGetRunner\x12\x18.runner.GetRunnerRequest\x1a\x0e.runner.Runner\x12U\n" +
	"\x10QuarantineRunner\x12\x1f.runner.QuarantineRunnerRequest\x1a .runner.QuarantineRunnerResponse\x12[\n" +
	"\x12UnquarantineRunner\x12!.runner.UnquarantineRunnerRequest\x1a\".runner.UnquarantineRunnerResponse\x12F\n" +
	"\vPauseRunner\x12\x1a.runner.PauseRunnerRequest\x1a\x1b.runner.PauseRunnerResponse\x12I\n" +
	"\fResumeRunner\x12\x1b.runner.ResumeRunnerRequest\x1a\x1c.runner.ResumeRunnerResponse\x12^\n" +
	"\x13UpdateNetworkPolicy\x12\".runner.UpdateNetworkPolicyRequest\x1a#.runner.UpdateNetworkPolicyResponse\x12U\n" +
	"\x10GetNetworkPolicy\x12\x1f.runner.GetNetworkPolicyRequest\x1a .runner.GetNetworkPolicyResponse2\xec\x02\n" +
	"\fControlPlane\x12@\n" +
	"\tGetRunner\x12\x18.runner.GetRunnerRequest\x1a\x19.runner.GetRunnerResponse\x12L\n" +
	"\rReleaseRunner\x12\x1c.runner.ReleaseRunnerRequest\x1a\x1d.runner.ReleaseRunnerResponse\x12I\n" +
	"\fRegisterHost\x12\x1b.runner.RegisterHostRequest\x1a\x1c.runner.RegisterHostResponse\x12D\n" +
	"\rHostHeartbeat\x12\x18.runner.HeartbeatRequest\x1a\x19.runner.HeartbeatResponse\x12;\n" +
	"\vGetSnapshot\x12\x1a.runner.GetSnapshotRequest\x1a\x10.runner.SnapshotB5Z3github.com/rahul-roy-glean/capsule/api/proto/runnerb\x06proto3"

var (
	file_api_proto_runner_proto_rawDescOnce sync.Once
	file_api_proto_runner_proto_rawDescData []byte
)

func file_api_proto_runner_proto_rawDescGZIP() []byte {
	file_api_proto_runner_proto_rawDescOnce.Do(func() {
		file_api_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_runner_proto_rawDesc), len(file_api_proto_runner_proto_rawDesc)))
	})
	return file_api_proto_runner_proto_rawDescData
}

var file_api_proto_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_proto_runner_proto_goTypes = []any{
	(RunnerState)(0),                     // 0: runner.RunnerState
	(HostState)(0),                       // 1: runner.HostState
	(*Resources)(nil),                    // 2: runner.Resources
	(*Runner)(nil),                       // 3: runner.Runner
	(*HostStatus)(nil),                   // 4: runner.HostStatus
	(*PoolStats)(nil),                    // 5: runner.PoolStats
	(*Snapshot)(nil),                     // 6: runner.Snapshot
	(*StartCommand)(nil),                 // 7: runner.StartCommand
	(*AllocateRunnerRequest)(nil),        // 8: runner.AllocateRunnerRequest
	(*AllocateRunnerResponse)(nil),       // 9: runner.AllocateRunnerResponse
	(*ReleaseRunnerRequest)(nil),         // 10: runner.ReleaseRunnerRequest
	(*ReleaseRunnerResponse)(nil),        // 11: runner.ReleaseRunnerResponse
	(*GetHostStatusRequest)(nil),         // 12: runner.GetHostStatusRequest
	(*HeartbeatRequest)(nil),             // 13: runner.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 14: runner.HeartbeatResponse
	(*ListRunnersRequest)(nil),           // 15: runner.ListRunnersRequest
	(*ListRunnersResponse)(nil),          // 16: runner.ListRunnersResponse
	(*GetRunnerRequest)(nil),             // 17: runner.GetRunnerRequest
	(*GetRunnerResponse)(nil),            // 18: runner.GetRunnerResponse
	(*QuarantineRunnerRequest)(nil),      // 19: runner.QuarantineRunnerRequest
	(*QuarantineRunnerResponse)(nil),     // 20: runner.QuarantineRunnerResponse
	(*UnquarantineRunnerRequest)(nil),    // 21: runner.UnquarantineRunnerRequest
	(*UnquarantineRunnerResponse)(nil),   // 22: runner.UnquarantineRunnerResponse
	(*RegisterHostRequest)(nil),          // 23: runner.RegisterHostRequest
	(*RegisterHostResponse)(nil),         // 24: runner.RegisterHostResponse
	(*GetSnapshotRequest)(nil),           // 25: runner.GetSnapshotRequest
	(*TriggerSnapshotBuildRequest)(nil),  // 26: runner.TriggerSnapshotBuildRequest
	(*TriggerSnapshotBuildResponse)(nil), // 27: runner.TriggerSnapshotBuildResponse
	(*PauseRunnerRequest)(nil),           // 28: runner.PauseRunnerRequest
	(*PauseRunnerResponse)(nil),          // 29: runner.PauseRunnerResponse
	(*ResumeRunnerRequest)(nil),          // 30: runner.ResumeRunnerRequest
	(*ResumeRunnerResponse)(nil),         // 31: runner.ResumeRunnerResponse
	(*UpdateNetworkPolicyRequest)(nil),   // 32: runner.UpdateNetworkPolicyRequest
	(*UpdateNetworkPolicyResponse)(nil),  // 33: runner.UpdateNetworkPolicyResponse
	(*GetNetworkPolicyRequest)(nil),      // 34: runner.GetNetworkPolicyRequest
	(*GetNetworkPolicyResponse)(nil),     // 35: runner.GetNetworkPolicyResponse
	nil,                                  // 36: runner.StartCommand.EnvEntry
	nil,                                  // 37: runner.AllocateRunnerRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),        // 38: google.protobuf.Timestamp
}
var file_api_proto_runner_proto_depIdxs = []int32{
	0,  // 0: runner.Runner.state:type_name -> runner.RunnerState
	38, // 1: runner.Runner.created_at:type_name -> google.protobuf.Timestamp
	38, // 2: runner.Runner.started_at:type_name -> google.protobuf.Timestamp
	2,  // 3: runner.Runner.resources:type_name -> runner.Resources
	1,  // 4: runner.HostStatus.state:type_name -> runner.HostState
	38, // 5: runner.HostStatus.snapshot_synced_at:type_name -> google.protobuf.Timestamp
	38, // 6: runner.HostStatus.last_heartbeat:type_name -> google.protobuf.Timestamp
	5,  // 7: runner.HostStatus.pool_stats:type_name -> runner.PoolStats
	38, // 8: runner.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	36, // 9: runner.StartCommand.env:type_name -> runner.StartCommand.EnvEntry
	2,  // 10: runner.AllocateRunnerRequest.resources:type_name -> runner.Resources
	37, // 11: runner.AllocateRunnerRequest.labels:type_name -> runner.AllocateRunnerRequest.LabelsEntry
	7,  // 12: runner.AllocateRunnerRequest.start_command:type_name -> runner.StartCommand
	3,  // 13: runner.AllocateRunnerResponse.runner:type_name -> runner.Runner
	4,  // 14: runner.HeartbeatRequest.status:type_name -> runner.HostStatus
	0,  // 15: runner.ListRunnersRequest.state_filter:type_name -> runner.RunnerState
	3,  // 16: runner.ListRunnersResponse.runners:type_name -> runner.Runner
	3,  // 17: runner.GetRunnerResponse.runner:type_name -> runner.Runner
	3,  // 18: runner.ResumeRunnerResponse.runner:type_name -> runner.Runner
	8,  // 19: runner.HostAgent.AllocateRunner:input_type -> runner.AllocateRunnerRequest
	10, // 20: runner.HostAgent.ReleaseRunner:input_type -> runner.ReleaseRunnerRequest
	12, // 21: runner.HostAgent.GetHostStatus:input_type -> runner.GetHostStatusRequest
	13, // 22: runner.HostAgent.Heartbeat:input_type -> runner.HeartbeatRequest
	15, // 23: runner.HostAgent.ListRunners:input_type -> runner.ListRunnersRequest
	17, // 24: runner.HostAgent.GetRunner:input_type -> runner.GetRunnerRequest
	19, // 25: runner.HostAgent.QuarantineRunner:input_type -> runner.QuarantineRunnerRequest
	21, // 26: runner.HostAgent.UnquarantineRunner:input_type -> runner.UnquarantineRunnerRequest
	28, // 27: runner.HostAgent.PauseRunner:input_type -> runner.PauseRunnerRequest
	30, // 28: runner.HostAgent.ResumeRunner:input_type -> runner.ResumeRunnerRequest
	32, // 29: runner.HostAgent.UpdateNetworkPolicy:input_type -> runner.UpdateNetworkPolicyRequest
	34, // 30: runner.HostAgent.GetNetworkPolicy:input_type -> runner.GetNetworkPolicyRequest
	17, // 31: runner.ControlPlane.GetRunner:input_type -> runner.GetRunnerRequest
	10, // 32: runner.ControlPlane.ReleaseRunner:input_type -> runner.ReleaseRunnerRequest
	23, // 33: runner.ControlPlane.RegisterHost:input_type -> runner.RegisterHostRequest
	13, // 34: runner.ControlPlane.HostHeartbeat:input_type -> runner.HeartbeatRequest
	25, // 35: runner.ControlPlane.GetSnapshot:input_type -> runner.GetSnapshotRequest
	9,  // 36: runner.HostAgent.AllocateRunner:output_type -> runner.AllocateRunnerResponse
	11, // 37: runner.HostAgent.ReleaseRunner:output_type -> runner.ReleaseRunnerResponse
	4,  // 38: runner.HostAgent.GetHostStatus:output_type -> runner.HostStatus
	14, // 39: runner.HostAgent.Heartbeat:output_type -> runner.HeartbeatResponse
	16, // 40: runner.HostAgent.ListRunners:output_type -> runner.ListRunnersResponse
	3,  // 41: runner.HostAgent.GetRunner:output_type -> runner.Runner
	20, // 42: runner.HostAgent.QuarantineRunner:output_type -> runner.QuarantineRunnerResponse
	22, // 43: runner.HostAgent.UnquarantineRunner:output_type -> runner.UnquarantineRunnerResponse
	29, // 44: runner.HostAgent.PauseRunner:output_type -> runner.PauseRunnerResponse
	31, // 45: runner.HostAgent.ResumeRunner:output_type -> runner.ResumeRunnerResponse
	33, // 46: runner.HostAgent.UpdateNetworkPolicy:output_type -> runner.UpdateNetworkPolicyResponse
	35, // 47: runner.HostAgent.GetNetworkPolicy:output_type -> runner.GetNetworkPolicyResponse
	18, // 48: runner.ControlPlane.GetRunner:output_type -> runner.GetRunnerResponse
	11, // 49: runner.ControlPlane.ReleaseRunner:output_type -> runner.ReleaseRunnerResponse
	24, // 50: runner.ControlPlane.RegisterHost:output_type -> runner.RegisterHostResponse
	14, // 51: runner.ControlPlane.HostHeartbeat:output_type -> runner.HeartbeatResponse
	6,  // 52: runner.ControlPlane.GetSnapshot:output_type -> runner.Snapshot
	36, // [36:53] is the sub-list for method output_type
	19, // [19:36] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_runner_proto_init() }
func file_api_proto_runner_proto_init() {
	if File_api_proto_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_runner_proto_rawDesc), len(file_api_proto_runner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_runner_proto_goTypes,
		DependencyIndexes: file_api_proto_runner_proto_depIdxs,
		EnumInfos:         file_api_proto_runner_proto_enumTypes,
		MessageInfos:      file_api_proto_runner_proto_msgTypes,
	}.Build()
	File_api_proto_runner_proto = out.File
	file_api_proto_runner_proto_goTypes = nil
	file_api_proto_runner_proto_depIdxs = nil
}
