// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/proto/runner.proto

package runner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAgent_AllocateRunner_FullMethodName      = "/runner.HostAgent/AllocateRunner"
	HostAgent_ReleaseRunner_FullMethodName       = "/runner.HostAgent/ReleaseRunner"
	HostAgent_GetHostStatus_FullMethodName       = "/runner.HostAgent/GetHostStatus"
	HostAgent_Heartbeat_FullMethodName           = "/runner.HostAgent/Heartbeat"
	HostAgent_ListRunners_FullMethodName         = "/runner.HostAgent/ListRunners"
	HostAgent_GetRunner_FullMethodName           = "/runner.HostAgent/GetRunner"
	HostAgent_QuarantineRunner_FullMethodName    = "/runner.HostAgent/QuarantineRunner"
	HostAgent_UnquarantineRunner_FullMethodName  = "/runner.HostAgent/UnquarantineRunner"
	HostAgent_PauseRunner_FullMethodName         = "/runner.HostAgent/PauseRunner"
	HostAgent_ResumeRunner_FullMethodName        = "/runner.HostAgent/ResumeRunner"
	HostAgent_UpdateNetworkPolicy_FullMethodName = "/runner.HostAgent/UpdateNetworkPolicy"
	HostAgent_GetNetworkPolicy_FullMethodName    = "/runner.HostAgent/GetNetworkPolicy"
)

// HostAgentClient is the client API for HostAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostAgent service runs on each Firecracker host VM
type HostAgentClient interface {
	// AllocateRunner allocates a new runner on this host
	AllocateRunner(ctx context.Context, in *AllocateRunnerRequest, opts ...grpc.CallOption) (*AllocateRunnerResponse, error)
	// ReleaseRunner releases a runner back to the pool or destroys it
	ReleaseRunner(ctx context.Context, in *ReleaseRunnerRequest, opts ...grpc.CallOption) (*ReleaseRunnerResponse, error)
	// GetHostStatus returns the current status of the host
	GetHostStatus(ctx context.Context, in *GetHostStatusRequest, opts ...grpc.CallOption) (*HostStatus, error)
	// Heartbeat sends a heartbeat to the control plane
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// ListRunners lists all runners on this host
	ListRunners(ctx context.Context, in *ListRunnersRequest, opts ...grpc.CallOption) (*ListRunnersResponse, error)
	// GetRunner gets details about a specific runner
	GetRunner(ctx context.Context, in *GetRunnerRequest, opts ...grpc.CallOption) (*Runner, error)
	// QuarantineRunner isolates a runner for debugging (e.g. block egress, pause VM)
	QuarantineRunner(ctx context.Context, in *QuarantineRunnerRequest, opts ...grpc.CallOption) (*QuarantineRunnerResponse, error)
	// UnquarantineRunner removes isolation and optionally resumes a paused runner
	UnquarantineRunner(ctx context.Context, in *UnquarantineRunnerRequest, opts ...grpc.CallOption) (*UnquarantineRunnerResponse, error)
	// PauseRunner snapshots a runner's session and suspends the VM
	PauseRunner(ctx context.Context, in *PauseRunnerRequest, opts ...grpc.CallOption) (*PauseRunnerResponse, error)
	// ResumeRunner restores a runner from a session snapshot
	ResumeRunner(ctx context.Context, in *ResumeRunnerRequest, opts ...grpc.CallOption) (*ResumeRunnerResponse, error)
	// UpdateNetworkPolicy updates the network policy for a running VM
	UpdateNetworkPolicy(ctx context.Context, in *UpdateNetworkPolicyRequest, opts ...grpc.CallOption) (*UpdateNetworkPolicyResponse, error)
	// GetNetworkPolicy returns the effective network policy for a runner
	GetNetworkPolicy(ctx context.Context, in *GetNetworkPolicyRequest, opts ...grpc.CallOption) (*GetNetworkPolicyResponse, error)
}

type hostAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAgentClient(cc grpc.ClientConnInterface) HostAgentClient {
	return &hostAgentClient{cc}
}

func (c *hostAgentClient) AllocateRunner(ctx context.Context, in *AllocateRunnerRequest, opts ...grpc.CallOption) (*AllocateRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateRunnerResponse)
	err := c.cc.Invoke(ctx, HostAgent_AllocateRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) ReleaseRunner(ctx context.Context, in *ReleaseRunnerRequest, opts ...grpc.CallOption) (*ReleaseRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseRunnerResponse)
	err := c.cc.Invoke(ctx, HostAgent_ReleaseRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) GetHostStatus(ctx context.Context, in *GetHostStatusRequest, opts ...grpc.CallOption) (*HostStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostStatus)
	err := c.cc.Invoke(ctx, HostAgent_GetHostStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, HostAgent_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) ListRunners(ctx context.Context, in *ListRunnersRequest, opts ...grpc.CallOption) (*ListRunnersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunnersResponse)
	err := c.cc.Invoke(ctx, HostAgent_ListRunners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) GetRunner(ctx context.Context, in *GetRunnerRequest, opts ...grpc.CallOption) (*Runner, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Runner)
	err := c.cc.Invoke(ctx, HostAgent_GetRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) QuarantineRunner(ctx context.Context, in *QuarantineRunnerRequest, opts ...grpc.CallOption) (*QuarantineRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuarantineRunnerResponse)
	err := c.cc.Invoke(ctx, HostAgent_QuarantineRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) UnquarantineRunner(ctx context.Context, in *UnquarantineRunnerRequest, opts ...grpc.CallOption) (*UnquarantineRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnquarantineRunnerResponse)
	err := c.cc.Invoke(ctx, HostAgent_UnquarantineRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) PauseRunner(ctx context.Context, in *PauseRunnerRequest, opts ...grpc.CallOption) (*PauseRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseRunnerResponse)
	err := c.cc.Invoke(ctx, HostAgent_PauseRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) ResumeRunner(ctx context.Context, in *ResumeRunnerRequest, opts ...grpc.CallOption) (*ResumeRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRunnerResponse)
	err := c.cc.Invoke(ctx, HostAgent_ResumeRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) UpdateNetworkPolicy(ctx context.Context, in *UpdateNetworkPolicyRequest, opts ...grpc.CallOption) (*UpdateNetworkPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNetworkPolicyResponse)
	err := c.cc.Invoke(ctx, HostAgent_UpdateNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) GetNetworkPolicy(ctx context.Context, in *GetNetworkPolicyRequest, opts ...grpc.CallOption) (*GetNetworkPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkPolicyResponse)
	err := c.cc.Invoke(ctx, HostAgent_GetNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAgentServer is the server API for HostAgent service.
// All implementations must embed UnimplementedHostAgentServer
// for forward compatibility.
//
// HostAgent service runs on each Firecracker host VM
type HostAgentServer interface {
	// AllocateRunner allocates a new runner on this host
	AllocateRunner(context.Context, *AllocateRunnerRequest) (*AllocateRunnerResponse, error)
	// ReleaseRunner releases a runner back to the pool or destroys it
	ReleaseRunner(context.Context, *ReleaseRunnerRequest) (*ReleaseRunnerResponse, error)
	// GetHostStatus returns the current status of the host
	GetHostStatus(context.Context, *GetHostStatusRequest) (*HostStatus, error)
	// Heartbeat sends a heartbeat to the control plane
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// ListRunners lists all runners on this host
	ListRunners(context.Context, *ListRunnersRequest) (*ListRunnersResponse, error)
	// GetRunner gets details about a specific runner
	GetRunner(context.Context, *GetRunnerRequest) (*Runner, error)
	// QuarantineRunner isolates a runner for debugging (e.g. block egress, pause VM)
	QuarantineRunner(context.Context, *QuarantineRunnerRequest) (*QuarantineRunnerResponse, error)
	// UnquarantineRunner removes isolation and optionally resumes a paused runner
	UnquarantineRunner(context.Context, *UnquarantineRunnerRequest) (*UnquarantineRunnerResponse, error)
	// PauseRunner snapshots a runner's session and suspends the VM
	PauseRunner(context.Context, *PauseRunnerRequest) (*PauseRunnerResponse, error)
	// ResumeRunner restores a runner from a session snapshot
	ResumeRunner(context.Context, *ResumeRunnerRequest) (*ResumeRunnerResponse, error)
	// UpdateNetworkPolicy updates the network policy for a running VM
	UpdateNetworkPolicy(context.Context, *UpdateNetworkPolicyRequest) (*UpdateNetworkPolicyResponse, error)
	// GetNetworkPolicy returns the effective network policy for a runner
	GetNetworkPolicy(context.Context, *GetNetworkPolicyRequest) (*GetNetworkPolicyResponse, error)
	mustEmbedUnimplementedHostAgentServer()
}

// UnimplementedHostAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAgentServer struct{}

func (UnimplementedHostAgentServer) AllocateRunner(context.Context, *AllocateRunnerRequest) (*AllocateRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateRunner not implemented")
}
func (UnimplementedHostAgentServer) ReleaseRunner(context.Context, *ReleaseRunnerRequest) (*ReleaseRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseRunner not implemented")
}
func (UnimplementedHostAgentServer) GetHostStatus(context.Context, *GetHostStatusRequest) (*HostStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostStatus not implemented")
}
func (UnimplementedHostAgentServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedHostAgentServer) ListRunners(context.Context, *ListRunnersRequest) (*ListRunnersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRunners not implemented")
}
func (UnimplementedHostAgentServer) GetRunner(context.Context, *GetRunnerRequest) (*Runner, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunner not implemented")
}
func (UnimplementedHostAgentServer) QuarantineRunner(context.Context, *QuarantineRunnerRequest) (*QuarantineRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuarantineRunner not implemented")
}
func (UnimplementedHostAgentServer) UnquarantineRunner(context.Context, *UnquarantineRunnerRequest) (*UnquarantineRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnquarantineRunner not implemented")
}
func (UnimplementedHostAgentServer) PauseRunner(context.Context, *PauseRunnerRequest) (*PauseRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseRunner not implemented")
}
func (UnimplementedHostAgentServer) ResumeRunner(context.Context, *ResumeRunnerRequest) (*ResumeRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRunner not implemented")
}
func (UnimplementedHostAgentServer) UpdateNetworkPolicy(context.Context, *UpdateNetworkPolicyRequest) (*UpdateNetworkPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNetworkPolicy not implemented")
}
func (UnimplementedHostAgentServer) GetNetworkPolicy(context.Context, *GetNetworkPolicyRequest) (*GetNetworkPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkPolicy not implemented")
}
func (UnimplementedHostAgentServer) mustEmbedUnimplementedHostAgentServer() {}
func (UnimplementedHostAgentServer) testEmbeddedByValue()                   {}

// UnsafeHostAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAgentServer will
// result in compilation errors.
type UnsafeHostAgentServer interface {
	mustEmbedUnimplementedHostAgentServer()
}

func RegisterHostAgentServer(s grpc.ServiceRegistrar, srv HostAgentServer) {
	// If the following call panics, it indicates UnimplementedHostAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAgent_ServiceDesc, srv)
}

func _HostAgent_AllocateRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).AllocateRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_AllocateRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).AllocateRunner(ctx, req.(*AllocateRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_ReleaseRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).ReleaseRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_ReleaseRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).ReleaseRunner(ctx, req.(*ReleaseRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_GetHostStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).GetHostStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_GetHostStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).GetHostStatus(ctx, req.(*GetHostStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_ListRunners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).ListRunners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_ListRunners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).ListRunners(ctx, req.(*ListRunnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_GetRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).GetRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_GetRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).GetRunner(ctx, req.(*GetRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_QuarantineRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuarantineRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).QuarantineRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_QuarantineRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).QuarantineRunner(ctx, req.(*QuarantineRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_UnquarantineRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnquarantineRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).UnquarantineRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_UnquarantineRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).UnquarantineRunner(ctx, req.(*UnquarantineRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_PauseRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).PauseRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_PauseRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).PauseRunner(ctx, req.(*PauseRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_ResumeRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).ResumeRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_ResumeRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).ResumeRunner(ctx, req.(*ResumeRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_UpdateNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).UpdateNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_UpdateNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).UpdateNetworkPolicy(ctx, req.(*UpdateNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_GetNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).GetNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_GetNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).GetNetworkPolicy(ctx, req.(*GetNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAgent_ServiceDesc is the grpc.ServiceDesc for HostAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.HostAgent",
	HandlerType: (*HostAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateRunner",
			Handler:    _HostAgent_AllocateRunner_Handler,
		},
		{
			MethodName: "ReleaseRunner",
			Handler:    _HostAgent_ReleaseRunner_Handler,
		},
		{
			MethodName: "GetHostStatus",
			Handler:    _HostAgent_GetHostStatus_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _HostAgent_Heartbeat_Handler,
		},
		{
			MethodName: "ListRunners",
			Handler:    _HostAgent_ListRunners_Handler,
		},
		{
			MethodName: "GetRunner",
			Handler:    _HostAgent_GetRunner_Handler,
		},
		{
			MethodName: "QuarantineRunner",
			Handler:    _HostAgent_QuarantineRunner_Handler,
		},
		{
			MethodName: "UnquarantineRunner",
			Handler:    _HostAgent_UnquarantineRunner_Handler,
		},
		{
			MethodName: "PauseRunner",
			Handler:    _HostAgent_PauseRunner_Handler,
		},
		{
			MethodName: "ResumeRunner",
			Handler:    _HostAgent_ResumeRunner_Handler,
		},
		{
			MethodName: "UpdateNetworkPolicy",
			Handler:    _HostAgent_UpdateNetworkPolicy_Handler,
		},
		{
			MethodName: "GetNetworkPolicy",
			Handler:    _HostAgent_GetNetworkPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/runner.proto",
}

const (
	ControlPlane_GetRunner_FullMethodName     = "/runner.ControlPlane/GetRunner"
	ControlPlane_ReleaseRunner_FullMethodName = "/runner.ControlPlane/ReleaseRunner"
	ControlPlane_RegisterHost_FullMethodName  = "/runner.ControlPlane/RegisterHost"
	ControlPlane_HostHeartbeat_FullMethodName = "/runner.ControlPlane/HostHeartbeat"
	ControlPlane_GetSnapshot_FullMethodName   = "/runner.ControlPlane/GetSnapshot"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane service runs in GKE
type ControlPlaneClient interface {
	// GetRunner requests a runner from the pool
	GetRunner(ctx context.Context, in *GetRunnerRequest, opts ...grpc.CallOption) (*GetRunnerResponse, error)
	// ReleaseRunner releases a runner
	ReleaseRunner(ctx context.Context, in *ReleaseRunnerRequest, opts ...grpc.CallOption) (*ReleaseRunnerResponse, error)
	// RegisterHost registers a new host with the control plane
	RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error)
	// HostHeartbeat receives heartbeats from hosts
	HostHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetSnapshot gets the current snapshot version
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) GetRunner(ctx context.Context, in *GetRunnerRequest, opts ...grpc.CallOption) (*GetRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReleaseRunner(ctx context.Context, in *ReleaseRunnerRequest, opts ...grpc.CallOption) (*ReleaseRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseRunnerResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReleaseRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHostResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) HostHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_HostHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, ControlPlane_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane service runs in GKE
type ControlPlaneServer interface {
	// GetRunner requests a runner from the pool
	GetRunner(context.Context, *GetRunnerRequest) (*GetRunnerResponse, error)
	// ReleaseRunner releases a runner
	ReleaseRunner(context.Context, *ReleaseRunnerRequest) (*ReleaseRunnerResponse, error)
	// RegisterHost registers a new host with the control plane
	RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error)
	// HostHeartbeat receives heartbeats from hosts
	HostHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetSnapshot gets the current snapshot version
	GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) GetRunner(context.Context, *GetRunnerRequest) (*GetRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunner not implemented")
}
func (UnimplementedControlPlaneServer) ReleaseRunner(context.Context, *ReleaseRunnerRequest) (*ReleaseRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseRunner not implemented")
}
func (UnimplementedControlPlaneServer) RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHost not implemented")
}
func (UnimplementedControlPlaneServer) HostHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostHeartbeat not implemented")
}
func (UnimplementedControlPlaneServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_GetRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetRunner(ctx, req.(*GetRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReleaseRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReleaseRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReleaseRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReleaseRunner(ctx, req.(*ReleaseRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterHost(ctx, req.(*RegisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_HostHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).HostHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_HostHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).HostHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunner",
			Handler:    _ControlPlane_GetRunner_Handler,
		},
		{
			MethodName: "ReleaseRunner",
			Handler:    _ControlPlane_ReleaseRunner_Handler,
		},
		{
			MethodName: "RegisterHost",
			Handler:    _ControlPlane_RegisterHost_Handler,
		},
		{
			MethodName: "HostHeartbeat",
			Handler:    _ControlPlane_HostHeartbeat_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _ControlPlane_GetSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/runner.proto",
}
