#!/usr/bin/env python3
# AUTO-GENERATED CODE - DO NOT MODIFY
#
# This file contains message types generated from the Anthropic Claude Code SDK specification.
# Any manual changes to this file will be lost when regenerated.
#
# Generated from: https://docs.anthropic.com/en/docs/claude-code/sdk#streaming-json-output
# Tool: Claude Code
# Warning: Do not edit this file manually - use the Claude Code generator instead

from __future__ import annotations

from datetime import datetime
from enum import Enum

try:
    from datetime import UTC
except ImportError:
    from datetime import timezone

    UTC = timezone.utc

from anthropic.types.message import Message
from anthropic.types.message_param import MessageParam
from pydantic.v1 import BaseModel
from pydantic.v1 import Field
from pydantic.v1 import validator


class ResultSubtype(str, Enum):
    """Result subtypes for SDKMessage."""

    SUCCESS = 'success'
    ERROR_MAX_TURNS = 'error_max_turns'
    ERROR_DURING_EXECUTION = 'error_during_execution'


class SystemSubtype(str, Enum):
    """System subtypes for SDKMessage."""

    INIT = 'init'


class PermissionMode(str, Enum):
    """Permission modes for system initialization."""

    DEFAULT = 'default'
    ACCEPT_EDITS = 'acceptEdits'
    BYPASS_PERMISSIONS = 'bypassPermissions'
    PLAN = 'plan'


class MCPServer(BaseModel):
    """MCP server configuration."""

    name: str = Field(..., description='Name of the MCP server')
    status: str = Field(..., description='Status of the MCP server')


class AnthropicArchivedMessage(BaseModel):
    """A single JSONL entry from Claude Code session logs."""

    timestamp: datetime | None = Field(None, description='Timestamp of the entry')
    message: Message | None = Field(None, description='Message from Anthropic SDK')

    @validator('timestamp', pre=True)
    def parse_timestamp(cls, v):
        """Parse ISO datetime string to UTC datetime object."""
        if isinstance(v, str):
            return datetime.fromisoformat(v.replace('Z', '+00:00')).astimezone(UTC)
        return v

    @validator('message', pre=True)
    def parse_message(cls, v):
        """Parse message, ignoring validation errors."""
        if v is None:
            return None
        # bypasses underlying validation + assumes what's passed in is always a valid json
        return Message.construct(**v)

    # Anthropic model contains typing.io
    # https://github.com/pydantic/pydantic/issues/5443
    class Config:
        extra = 'ignore'
        arbitrary_types_allowed = True


class AssistantMessage(BaseModel):
    """An assistant message from the SDKMessage union."""

    type: str = Field(default='assistant', description='Message type')
    message: Message = Field(..., description='Message from Anthropic SDK')
    session_id: str = Field(..., description='Session identifier')

    @validator('message', pre=True)
    def parse_message(cls, v):
        """Parse message dict to Message instance."""
        if isinstance(v, dict):
            return Message.construct(**v)
        return v

    # Anthropic model contains typing.io
    # https://github.com/pydantic/pydantic/issues/5443
    class Config:
        arbitrary_types_allowed = True


class UserMessage(BaseModel):
    """A user message from the SDKMessage union."""

    type: str = Field(default='user', description='Message type')
    message: MessageParam = Field(..., description='MessageParam from Anthropic SDK')
    session_id: str = Field(..., description='Session identifier')

    # Anthropic model contains typing.io
    # https://github.com/pydantic/pydantic/issues/5443
    class Config:
        arbitrary_types_allowed = True


class SuccessResult(BaseModel):
    """Success result message from the SDKMessage union."""

    type: str = Field(default='result', description='Message type')
    subtype: ResultSubtype = Field(default=ResultSubtype.SUCCESS, description='Result subtype')
    duration_ms: float = Field(..., description='Total duration in milliseconds')
    duration_api_ms: float = Field(..., description='API duration in milliseconds')
    is_error: bool = Field(..., description='Whether this is an error result')
    num_turns: int = Field(..., description='Number of turns in the conversation')
    result: str = Field(..., description='Result content')
    session_id: str = Field(..., description='Session identifier')
    total_cost_usd: float = Field(..., description='Total cost in USD')


class ErrorResult(BaseModel):
    """Error result message from the SDKMessage union."""

    type: str = Field(default='result', description='Message type')
    subtype: ResultSubtype = Field(..., description='Error subtype')
    duration_ms: float = Field(..., description='Total duration in milliseconds')
    duration_api_ms: float = Field(..., description='API duration in milliseconds')
    is_error: bool = Field(..., description='Whether this is an error result')
    num_turns: int = Field(..., description='Number of turns in the conversation')
    session_id: str = Field(..., description='Session identifier')
    total_cost_usd: float = Field(..., description='Total cost in USD')


class SystemInitMessage(BaseModel):
    """System initialization message from the SDKMessage union."""

    type: str = Field(default='system', description='Message type')
    subtype: SystemSubtype = Field(default=SystemSubtype.INIT, description='System subtype')
    api_key_source: str = Field(..., alias='apiKeySource', description='Source of the API key')
    cwd: str = Field(..., description='Current working directory')
    session_id: str = Field(..., description='Session identifier')
    tools: list[str] = Field(..., description='List of available tools')
    mcp_servers: list[MCPServer] = Field(..., description='MCP server configurations')
    model: str = Field(..., description='Model being used')
    permission_mode: PermissionMode = Field(..., alias='permissionMode', description='Permission mode')


class AnthropicSDKMessage(BaseModel):
    """Pydantic class for handling Anthropic SDK messages with parsing logic."""

    message: AssistantMessage | UserMessage | SuccessResult | ErrorResult | SystemInitMessage

    @classmethod
    def parse_sdk_message(cls, json_data: dict) -> AnthropicSDKMessage:
        """Parse JSON data into the appropriate SDKMessage Pydantic model."""
        msg_type = json_data.get('type', '')
        msg_subtype = json_data.get('subtype', '')

        if msg_type == 'assistant':
            return AnthropicSDKMessage(message=AssistantMessage(**json_data))
        elif msg_type == 'user':
            return AnthropicSDKMessage(message=UserMessage(**json_data))
        elif msg_type == 'result':
            if msg_subtype == 'success':
                return AnthropicSDKMessage(message=SuccessResult(**json_data))
            else:
                return AnthropicSDKMessage(message=ErrorResult(**json_data))
        elif msg_type == 'system' and msg_subtype == 'init':
            return AnthropicSDKMessage(message=SystemInitMessage(**json_data))
        else:
            # Fallback: create a basic message structure
            raise ValueError(f'Unknown message type: {msg_type} with subtype: {msg_subtype}')
